language: node_js
node_js:
- '12'
cache: npm
script:
- CI=false npm run build
branches:
  only:
  - master
  - develop
deploy:
- provider: firebase
  project: "charitydiscount"
  only: hosting:main
  on:
    branch: master
  skip_cleanup: true
  token:
    secure: fKP28i3Rwr9S9MjWs0NpShPWsgFFI3aOqOVDcQ734/5It9OeUv6zMG245etN13xLH3a3Br+WDIxtLY6uNnZIBKhS6ZtGcF92efzqQRN6sAWelk7rOd1LwkJyG3X7gyqX29fClYCHE3UHnQMyZk6RLaESWxLu0/3sGk4QF/GlClXM2cibtPy6gkGJL5fY/dWOeab3JHp4YE9UeZQYRraBsB1B3F/l9DDXnrzUEA4J7ReL+0hWwjZOx4YC8ZegzODfKMp4DQUPa8ZCH8KnMSU5/vtjihEoCwrvG/oXKCBXrkPHiU/wSCQ8q8h1NsJDOkfH9AHfZ5u2f8Ks2arpfOjfQVjdZa6hia+brJIHU2VFOBttarZcpEKoE15zeH/uuh/cU9NxYiFOO8PGJz1EaTi5x21Xr/52y+KTdJrgeNlpnJGeKrNxmq1Of/VQ5t7U9yQKcnyhykV9U9HItmDyrA3kWXEoOJNGRWkWQe3lGpp3AVmy+dey1lW/3EW+mWDscQoi0KwhJRxdhmhwAZRg0CxvO+Dbo0k/LjAXc1wvt4gu1H8yFmanH36Y5YiLnDF5IthcmHNkJeTuWLFm2eghgF/ou7rI27GtHg2ltG/EIJ7DPSLUjRWd/uytrIjv3AwZBxMtqxAcuUpYNAIi07Fi+Pfcn39JyE9OzSVs2x69E1kRZPQ=
- provider: firebase
  project: "charitydiscount-test"
  only: hosting:main
  on:
    branch: develop
  skip_cleanup: true
  token:
    secure: ihBV1wISAWfUk4FU4WPWDbMuCBeOi67HIL2KFNWVUbfr8zVzu0N4SINa8CI9HUFWhAbx3t64zITB22bm+PtJcAIbtSPRkSsfKpjwgzAcRwcg3yJ23D60yHFUHEs52kWAeXtgSFlit8+eOosHd6q9TS62qeCtp0vmouY4Oi8i7mOCALUVLaujT8tw5NY2nIMr96ogOP69BKpJ8fAhWuTBjWBDER3W23iig4xNkXd6oZhLU3TPscdf6Ph8i2Qe2Ay9yXt5YxGBbVQjLx4StFTPasxkYacNLG70Cid6VszC7S3BLspxQNo/TzI8O8eGYiZgJeOzmBpOKgAtst9ZZ7OfOfMI1AqTUHCuH3IsOPQD1dj86IHGZFaNgW8iCOLtA0opzWMu4LEhU82RmRMb/CiAO73NI4VcTXfwdJaReHfXNS+XqXIFzZf6zd7u8ruF8ii9kx/mzMU25gmxRKF4mTiMIhYrjKViT5Bd96bB8OnBYNuBC+DiKsirYoPY++BVJdIrsY4q8mkyJgK3sXdnynKkdsgLt9TLQDKgoNHKRG8yFcmSK69PTpaBymh3l3OcijnkdSJUmw+T8y+GVPtgMbyYnKSho0zfzWteoZkcWNrJ9XK9T1IHsPEcG/CDhFqzxiquqYtFMXV6ADJSSsoW4n6hhTQoNIM3J6PAm5IUA17Uu/U=
