export enum NavigationActionTypes {
    SET_STAGE_ACTION = 'SET_STAGE_ACTION',
    RESET_STAGE_ACTION = 'RESET_STAGE_ACTION'
}

export enum LoginActionTypes {
    SET_LOGGED_USER_ACTION = 'SET_LOGGED_USER_ACTION',
    RESET_LOGGED_USER_ACTION = 'RESET_LOGGED_USER_ACTION',
}